name: Docker Build and Deploy
on: workflow_dispatch
jobs:
  BuildJob:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v4.2.2
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: run the maven build
        run: mvn package
